name: React app deployment

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git config --global credential.helper wincred

          git remote set-url origin https://$user_name:${{ secrets.GITHUB_TOKEN }}@github.com/${repository}


          NODE_DEBUG=gh-pages npm run deploy
        env:
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          REACT_APP_GIST_ID: ${{ secrets.REACT_APP_GIST_ID }}
          REACT_APP_GIST_TOKEN: ${{ secrets.REACT_APP_GIST_TOKEN }}
